### PR TITLE
Update preview GIF

### PR DESCRIPTION
**Pull request by SimonMarquis**
See #43

### CODE REVIEW

**Comment by SimonMarquis** [comment]
I don't know if it is because of Android 13 or if you changed the behavior, but the notification bar no longer disappear after killing/restarting with Venom.
I had to quickly close it in the recording to be able to view the intermediate Activity.

**Comment by YarikSOffice** [comment]
@SimonMarquis you are right, it's gonna be fixed via https://github.com/YarikSOffice/venom/pull/47

**Comment by YarikSOffice** [comment]
@SimonMarquis I just realized that something is wrong with this video.
The restart process starts from Screen #4, but finally lands on Screen #3 which is a bug.

It's been happening prior to the latest changes as well, there is an issue somewhere that I was not able to catch and fix.

**Comment by SimonMarquis** [comment]
FWIW I'm not able to reproduce it on my physical device, nor on a new emulator instance.
I wonder if the emulator I used was broken in some ways...
Are you able to reproduce this behavior on your end?

**Comment by YarikSOffice** [comment]
I can't reproduce it right now, but it happens once in a while I believe, 1 out of 100.

**Comment by SimonMarquis** [comment]
I've updated the previews with the expected behavior until we find out what is causing the issue.

**Comment by SimonMarquis** [comment]
If it happens 1 out of 100 it can be a timing issue.

**Comment by SimonMarquis** [comment]
There is also one weird behavior, which appears after a restart, when returning from the 2nd Activity to the 1st. The transition is different:

https://user-images.githubusercontent.com/1921278/209438401-6646c287-7eae-48a4-9ca3-7bd00bf5a9c9.mp4

**Comment by YarikSOffice** [comment]
yeah, you are right, perhaps a side effect of the latest changes in android 13 in regards to the back navigation and transitions.
Hopefully, it does not affect Venom's capabilities.

**Pull request merged**
