### PR TITLE
add android 12 support

### LINKED ISSUE #27: Support Android 12
Android 12 has changes with pending intents which requires declaration of mutability. https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

### PR DESCRIPTION
**Pull request by Skyyo**
made a few changes required to use Venom when targeting API 31. closes #27

### CODE REVIEW

**Comment by Skyyo** [comment]
Hello @YarikSOffice , 
can you please approve the workflow to run? This is a pretty small PR, but should help a lot of users who already target Android 12

**Comment by YarikSOffice** [comment]
@Skyyo Nice work! thanks for the contribution Denis 
Could you look into the lint errors to make the build pass?

**Comment by Skyyo** [comment]
Thanks for fast response @YarikSOffice. Will look into it

**Comment by Skyyo** [comment]
lint should be passing now @YarikSOffice . Bumped Kotlin, AppCompat & ConstraintLayout versions for it.

**Comment by Skyyo** [comment]
@YarikSOffice is there any chance we'll get this fix in the library any time soon?

**Comment by YarikSOffice** [comment]
@Skyyo Thanks again for your contribution! I'm going to prepare a new release now

**Comment by YarikSOffice** [comment]
[Venom 0.5.0](https://github.com/YarikSOffice/venom/releases/tag/0.5.0) is already live 👍

**Comment by Skyyo** [comment]
thanks for super fast reactions @YarikSOffice !

**Comment by ColtonIdle** [comment]
WOOOO

**Pull request merged**
